- name: install nginx
  hosts: all
  become: yes
  tasks:
    - name: ls
      ansible.builtin.shell: "ls -la"
      register: info
    - name: print
      ansible.builtin.debug:
        msg: "before: {{info.stdout}}" 
    - name: copy file
      ansible.builtin.copy:
        src: ~/ngix.yaml
        dest: ~/
    - name: ls
      ansible.builtin.shell: "ls -la"
      register: info
    - name: print
      ansible.builtin.debug:
        msg: {{info.stdout}} 
