- name: install nginx
  hosts: all
  become: yes
  tasks:
    - name: ls
      ansible.builtin.shell: "rm ~/n*"
      ignore_errors: yes
    - name: ls
      ansible.builtin.shell: "pwd"
      ignore_errors: yes
    - name: ls
      ansible.builtin.shell: "ls ~/"
      register: info
    - name: print
      ansible.builtin.debug:
        msg: "before: {{info}}" 
    - name: copy file
      ansible.builtin.copy:
        src: /home/ansible/Ansible/nginx.yaml
        dest: ~/
    - name: ls
      ansible.builtin.shell: "ls ~/"
      register: info
    - name: print
      ansible.builtin.debug:
        msg: "{{info}}" 
