---
- name: create a file
  hosts: all
  become: yes
  tasks:
    - name: create a file
      ansible.builtin.file:
        path: /home/ec2-user/file.txt
        state: touch
        owner: ec2-user
        group: ec2-user
        mode: "0777"
