---
- name: httpd
  hosts: all
  vars: 
    - name: Nandi
  become: yes
  tasks:
    - name: install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    - name: copy html
      ansible.builtin.template:
        src: ~/Ansible/index.html
        dest: /var/www/html/