---
- name: httpd
  hosts: all
  become: yes
  tasks:
    - name: install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present
    - name: start httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
    